# Generated by Django 3.1.2 on 2021-09-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0245f4a2-779f-40f5-8109-ec123aa8746c'), editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=63, verbose_name='Name of service')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost of service')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR')], default='RUB', max_length=6, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0245f4a2-779f-40f5-8109-ec123aa8746c'), editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('number_walet', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Number of wallet')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0245f4a2-779f-40f5-8109-ec123aa8746c'), editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transaction', to='WalletController.service', verbose_name='Service')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transactions', to='WalletController.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Service buy',
                'verbose_name_plural': 'Services buy',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0245f4a2-779f-40f5-8109-ec123aa8746c'), editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('wallet_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_received', to='WalletController.wallet', verbose_name='Sender received')),
                ('wallet_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_send', to='WalletController.wallet', verbose_name="Sender's wallet")),
            ],
            options={
                'verbose_name': 'Base Entity',
                'verbose_name_plural': 'Base Entities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantOuter',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0245f4a2-779f-40f5-8109-ec123aa8746c'), editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, verbose_name='Card number')),
                ('merchant_type', models.CharField(max_length=10, verbose_name='Merchant type')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=2021, max_length=4, verbose_name='Year')),
                ('month', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default=9, max_length=8, verbose_name='Month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MerchantOuter', to='WalletController.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
    ]
