# Generated by Django 3.1.2 on 2021-09-27 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('number_walet', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Number of wallet')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.customuser')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('a068ad90-a65f-4399-83e2-8bd05de8be55'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of transaction')),
                ('transaction_from', models.CharField(max_length=50, null=True, verbose_name='Transaction action from - wallet id,merchant,service')),
                ('transaction_to', models.CharField(max_length=50, null=True, verbose_name='Transaction action from - wallet id,merchant,service')),
                ('transaction_type', models.CharField(choices=[('MERCHANT_INCOME', 'MERCHANT_INCOME'), ('SERVICE_OUTCOME', 'SERVICE_OUTCOME'), ('USER_2_USER_OUTCOME', 'USER_2_USER_OUTCOME'), ('USER_2_USER_INCOME', 'SERVICE_INCOME')], max_length=20, verbose_name='Transaction Type')),
                ('wallets', models.ManyToManyField(related_name='transactions', to='WalletController.Wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
