# Generated by Django 3.1.2 on 2021-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Users phone number', max_length=13, unique=True, verbose_name='Phone'),
        ),
    ]
